# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
nlmmperm <- function(x, z, y, clust, block, samples, betaprior, phivprior, psivprior) {
    .Call('_trcpp_nlmmperm', PACKAGE = 'trcpp', x, z, y, clust, block, samples, betaprior, phivprior, psivprior)
}

#' @export
nlmperm <- function(x, y, block, samples, betaprior, psiprior) {
    .Call('_trcpp_nlmperm', PACKAGE = 'trcpp', x, y, block, samples, betaprior, psiprior)
}

