# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
bernlong <- function(y, x, z, m, block, samples, betaprior, phivprior, betadelt, zetadelt) {
    .Call('_trcpp_bernlong', PACKAGE = 'trcpp', y, x, z, m, block, samples, betaprior, phivprior, betadelt, zetadelt)
}

#' @export
lmerlong <- function(y, x, z, m, block, samples, betaprior, phivprior, psivprior) {
    .Call('_trcpp_lmerlong', PACKAGE = 'trcpp', y, x, z, m, block, samples, betaprior, phivprior, psivprior)
}

#' @export
lmerperm <- function(x, z, y, clust, block, samples, betaprior, phivprior, psivprior) {
    .Call('_trcpp_lmerperm', PACKAGE = 'trcpp', x, z, y, clust, block, samples, betaprior, phivprior, psivprior)
}

#' @export
rnormsum <- function(mu, sigma, t, n, delta) {
    .Call('_trcpp_rnormsum', PACKAGE = 'trcpp', mu, sigma, t, n, delta)
}

#' @export
multrjct <- function(prb, s) {
    .Call('_trcpp_multrjct', PACKAGE = 'trcpp', prb, s)
}

